
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gophermart
      POSTGRES_DB: gophermart
      POSTGRES_PASSWORD: gophermart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: